-- Lets a parent (admin or co-admin) delete a timesheet generated by accident
-- or with incorrect dates, plus its associated payment record, as long as
-- neither has been marked paid/locked yet.
--
-- The original timesheets_delete_manager policy only allowed deleting a
-- timesheet while status = 'draft', but Pay.tsx always inserts a generated
-- timesheet directly as 'approved', so no generated timesheet could ever
-- actually be deleted. payment_records_delete_admin was also admin-only,
-- inconsistent with every other manager-level action on this page (generate,
-- mark paid), which allow co-admins too.
--
-- Run this against any database that already applied 0002_rls.sql.

drop policy if exists timesheets_delete_manager on public.timesheets;

create policy timesheets_delete_manager on public.timesheets
  for delete
  using (
    public.is_parent_or_coadmin(public.household_id_for_caregiver(caregiver_id))
    and status not in ('paid', 'locked')
  );

drop policy if exists payment_records_delete_admin on public.payment_records;
drop policy if exists payment_records_delete_manager on public.payment_records;

create policy payment_records_delete_manager on public.payment_records
  for delete
  using (
    public.is_parent_or_coadmin(public.household_id_for_caregiver(caregiver_id))
    and status <> 'paid'
  );
